### ISSUE TITLE
Forecast showing same temperature for min and max

### ISSUE THREAD

**Issue by AuxProc** [freakified/TimeStylePebble#71] opened 2016-05-11 19:24 UTC
The forecast complication has been showing the same minimum and max temperature for quite a while now.  For clarification, its not that the forecast temperatures doesnt update, but that everytime it updates the same two numbers are shown from the minimum and maximum.

**Comment by tilden** [comment] 2016-05-12 16:53
Yeah, this is a definite issue. The problem is, OpenWeatherMap doesn't actually offer daily forecasts for free, so I'm actually just pulling the next 24 hours of hourly forecasts and using the min/max temps. It's possible that if I use the next 48 hours this issue will happen less.

**Comment by AuxProc** [comment] 2016-05-13 16:57
The two numbers have been showing the same temperature for at least the past month or more.  I have never seen it show different numbers in the min and max during this time.  If it was correctly pulling hourly temps for the next 24 hours, I would expect the two numbers to be different at least some of the time, but its never different.

**Comment by tilden** [comment] 2016-05-29 14:52
Fixed in version 6.0

**Closed as completed by tilden** 2016-05-29 14:52 UTC
