### ISSUE TITLE
Time widget to the sidebar

### ISSUE THREAD

**Issue by derrij** [freakified/TimeStylePebble#35] opened 2015-12-10 06:51 UTC
Please add Time widget  to the sidebar. 
It adds ability to read time under the cuff.
Thank you.
![time_widget](https://cloud.githubusercontent.com/assets/3122812/11708757/64f5938a-9f1a-11e5-91b3-d71bc28e2ccc.jpg)

**Comment by KyberMage** [comment] 2016-01-30 15:00
I was able to add this. I did run into compile errors right off the bat with the master branch though. Maybe the owner @tilden can comment on this error message: 

../src/clock_digit.c:131:22: error: invalid operands to binary == (have 'GColor' and 'GColor8')

There are a few of these existing from a fresh pull of master. I am able to build fine if I comment those lines out (they all involve checks for APLITE watches).

I also added the current time widget option and images to the gh-pages settings page.

![image](https://cloud.githubusercontent.com/assets/2174762/12696401/16d28b90-c738-11e5-9efc-74db51872110.png)

![image](https://cloud.githubusercontent.com/assets/2174762/12703725/fc6e1b8a-c817-11e5-9e3c-e24b8450e8a8.png)

**Comment by tilden** [comment] 2016-02-01 12:52
Awesome! Yeah, the Aplite related errors are caused by the changes for black and white watches in SDK 3.8. I've already fixed them in the other branch, but I need to finish adding grey support before I merge it to master and release.

I'm hoping to get that version pushed by this week, then I can work on merging your code. Go ahead and make a pull request!

**Comment by tilden** [comment] 2016-02-09 21:41
This has been merged and added to the 4.8 release. Thanks for the contribution!

**Closed as completed by tilden** 2016-02-09 21:41 UTC
Labels: enhancement
