### ISSUE TITLE
Weather off by 100

### ISSUE THREAD

**Issue by mccurdyc** [freakified/TimeStylePebble#67] opened 2016-03-25 02:09 UTC
The sidebar weather is off by 100 degrees Fahrenheit. I have tried switching watchfaces, restarting Pebble and looking for updates, to no avail.

**Comment by mccurdyc** [comment] 2016-03-25 02:10
I have also tried automatic and manual location. For an image check out my Twitter (McCurdyColton)

**Comment by tilden** [comment] 2016-03-25 02:46
Duplicate of #66

**Closed as completed by tilden** 2016-03-25 02:46 UTC
