### ISSUE TITLE
Heartrate is not displayed when bluetooth is off

### ISSUE THREAD

**Issue by adobi** [freakified/TimeStylePebble#93] opened 2016-11-19 20:06 UTC

**Comment by tilden** [comment] 2016-11-20 13:36
Is the heart rate widget in the middle slot? If so, try putting it in the top slot -- it's possible that the middle slot is just being replaced by the disconnect indication.

**Comment by adobi** [comment] 2016-11-20 13:43
Okey. So when the watch and the phone are not connected, an indicator is displayed always?

**Comment by tilden** [comment] 2016-11-25 15:30
Correct. There is currently an issue for an option to hide that icon, issue #65

**Comment by tilden** [comment] 2016-11-25 15:30
Closing as a duplicate of issue #65

**Closed as completed by tilden** 2016-11-25 15:30 UTC
Labels: duplicate
